apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vdpa-net-a
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/vdpa_dpdk_a
spec:
  config: '{
  "type": "vdpa",
  "cniVersion": "0.3.1",
  "name": "vdpa-network-a",
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
  "logFile": "/var/log/vdpa-cni-a.log",
  "logLevel": "debug"
}'
