apiVersion: v1
kind: Pod
metadata:
  name: vdpa-grpc-server
spec:
  containers:
  - name: vdpa-grpc-server
    image: nfvpe/vdpa-grpc-server
    imagePullPolicy: Never
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
