apiVersion: v1
kind: Pod
metadata:
  name: vdpa-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: vdpa-net-a, vdpa-net-b
spec:
  containers:
  - name: vdpa-example
    image: dpdk-app-centos:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: false
    - mountPath: /var/lib/cni/usrspcni/
      name: shared-dir
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 1Gi
        intel.com/intel_vdpa_dpdk_a: '1'
        intel.com/intel_vdpa_dpdk_b: '1'
      limits:
        hugepages-1Gi: 2Gi
        intel.com/intel_vdpa_dpdk_a: '1'
        intel.com/intel_vdpa_dpdk_b: '1'
    #command: ["sleep", "infinity"]
  volumes:
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: shared-dir
    hostPath:
      path: /var/run/vdpa/vhost/
  - name: hugepage
    emptyDir:
      medium: HugePages
