---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vdpa-cni-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: vdpa-cni
    name: vdpa-cni
spec:
  selector:
    matchLabels:
      name: vdpa-cni
  template:
    metadata:
      labels:
        tier: node
        app: vdpa-cni
        name: vdpa-cni
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-vdpa-cni
        image: vdpa-cni
        imagePullPolicy: Never
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
